/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Districts
         * @description Serve simplified Rwanda district boundaries as GeoJSON.
         */
        get: operations["get_districts_api_v1_districts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/yield-gap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Yield Gap
         * @description Per-district actual vs. attainable yield and the gap between them, for one
         *     crop x season x year. Returns every district with data for that combination,
         *     including "suppressed" (low-reliability) rows, per CLAUDE.md golden rule 6: the
         *     frontend greys those out, this endpoint does not hide them.
         */
        get: operations["get_yield_gap_api_v1_yield_gap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Drivers
         * @description SHAP-based driver ranking for one crop, either global or for one district.
         *     Includes "suppressed" district rows (too few plots), not hidden, per golden rule 6.
         */
        get: operations["get_drivers_api_v1_drivers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backtest
         * @description Nowcast leave-one-year-out backtest metrics (MAPE, its spread across the held-out
         *     years, and MAE in kg/ha) for every model and lead time, for one crop. See
         *     docs/decisions.md 2026-09-24 for the honest verdict on what these numbers mean.
         */
        get: operations["get_backtest_api_v1_backtest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nowcast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Nowcast
         * @description Early yield estimate for every district, for one crop x season x year x lead
         *     time. Empty list if that combination has no backtest coverage (see NowcastRow
         *     docstring: served rows are historical leave-one-year-out predictions, not live
         *     in-season forecasts).
         */
        get: operations["get_nowcast_api_v1_nowcast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nowcast/{code}/curve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Nowcast Curve
         * @description NDVI and rainfall curve (one point per lead time) vs climatology, for one
         *     district x season x year. Not crop-specific. 404 for an unknown district code.
         */
        get: operations["get_nowcast_curve_api_v1_nowcast__code__curve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Meta
         * @description Lets the frontend read scope (years, districts) from the real data rather than
         *     hardcoding it, so it can never drift from what data/public/ actually contains.
         */
        get: operations["get_meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Kpis
         * @description National-level yield estimate for every MVP crop, for one season x year, from
         *     src/agritwin/survey/'s national geo_level rows. One row per crop with its own CI and
         *     reliability, not a single blended national number.
         */
        get: operations["get_kpis_api_v1_kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/districts/{code}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get District Profile
         * @description Composite view for one district x crop, assembled from already-precomputed
         *     data/public/ files: yield trend and yield-gap trend across years, this district's
         *     top SHAP drivers, and its peer districts (same k-means zone). No new modeling.
         */
        get: operations["get_district_profile_api_v1_districts__code__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenario/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scenario
         * @description The 16 lever-configuration means and bootstrap intervals for one district x crop,
         *     per src/agritwin/models/scenario.py. Always model-based, not causal (CLAUDE.md rule
         *     5).
         */
        get: operations["get_scenario_api_v1_scenario__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/briefs/{code}.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Brief
         * @description Serves the precomputed one-page district brief PDF from data/public/briefs/.
         *
         *     `crop` and `season` are accepted, per api/CLAUDE.md's documented
         *     `?crop&season` signature, but have no effect: src/agritwin/export/briefs.py builds
         *     one brief per district covering all 4 MVP crops on one page, not one per
         *     district x crop x season (see docs/decisions.md 2026-09-24), so there is nothing
         *     to filter to. Same pattern as DriverRow/BacktestRow's unused `season` parameter.
         */
        get: operations["get_brief_api_v1_briefs__code__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BacktestRow
         * @description One model's nowcast backtest metrics for one crop x lead time, per
         *     src/agritwin/models/nowcast.py's leave_one_year_out_cv. Same season caveat as
         *     DriverRow: data/public/nowcast_backtest.csv has no season column, the backtest
         *     pools Season A and B together per crop.
         */
        BacktestRow: {
            crop: components["schemas"]["Crop"];
            /** Lead Months */
            lead_months: number;
            /** Model */
            model: string;
            /** Mape Pct */
            mape_pct: number;
            /** Mape Std Across Years */
            mape_std_across_years: number;
            /** Mae Kg Ha */
            mae_kg_ha: number;
            /** N Years Tested */
            n_years_tested: number;
        };
        /**
         * Crop
         * @description MVP crop scope, per config/crops.yaml canonical and config/settings.yaml scope.crops.
         * @enum {string}
         */
        Crop: "maize" | "beans" | "irish_potato" | "sorghum";
        /**
         * DistrictInfo
         * @description Minimal district identity: code plus display name.
         */
        DistrictInfo: {
            /** District Code */
            district_code: number;
            /** District Name */
            district_name: string;
        };
        /**
         * DistrictProfile
         * @description Composite per-district view assembled from data/public/ only (no new modeling):
         *     yield trend and yield-gap trend across years, this district's top SHAP drivers, and
         *     its peer districts (same k-means zone, per src/agritwin/models/attainable.py's
         *     zone assignment, the same fallback used in place of a real agro-ecological-zone
         *     layer).
         */
        DistrictProfile: {
            /** District Code */
            district_code: number;
            /** District Name */
            district_name: string;
            crop: components["schemas"]["Crop"];
            /** Yield Trend */
            yield_trend: components["schemas"]["YearlyYield"][];
            /** Gap Trend */
            gap_trend: components["schemas"]["YearlyGap"][];
            /** Top Drivers */
            top_drivers: components["schemas"]["DriverRow"][];
            /** Peer Districts */
            peer_districts: components["schemas"]["DistrictInfo"][];
        };
        /**
         * DriverRow
         * @description One feature's SHAP-based association with log-yield for one crop, per
         *     src/agritwin/models/drivers.py. district_code/n_plots/reliability are null for the
         *     global (all-districts) summary and set for a per-district one (?district= given);
         *     a "suppressed" district row is still returned, not hidden, per golden rule 6.
         *
         *     Known deviation from api/CLAUDE.md's ?crop&season[&district] signature: the driver
         *     model pools Season A and Season B together per crop (data/public/drivers.csv and
         *     drivers_by_district.csv carry no season column), so there is no season-specific
         *     result to filter to. `season` is accepted but currently has no effect; see
         *     docs/decisions.md for why re-training per season was not done as part of this
         *     endpoint.
         */
        DriverRow: {
            crop: components["schemas"]["Crop"];
            /** District Code */
            district_code?: number | null;
            /** Feature */
            feature: string;
            /** Mean Abs Shap */
            mean_abs_shap: number;
            /** Direction */
            direction: string;
            /** N Plots */
            n_plots?: number | null;
            reliability?: components["schemas"]["Reliability"] | null;
        };
        /**
         * GeoJSONResponse
         * @description GeoJSON FeatureCollection response.
         * @example {
         *       "features": [
         *         {
         *           "geometry": {
         *             "coordinates": [
         *               [
         *                 [
         *                   29,
         *                   -2
         *                 ],
         *                 [
         *                   29.1,
         *                   -2
         *                 ]
         *               ]
         *             ],
         *             "type": "Polygon"
         *           },
         *           "properties": {
         *             "district_name": "Kigali",
         *             "gaul_district_code": 1,
         *             "district_code": 12
         *           },
         *           "type": "Feature"
         *         }
         *       ],
         *       "type": "FeatureCollection"
         *     }
         */
        GeoJSONResponse: {
            /**
             * Type
             * @default FeatureCollection
             */
            type: string;
            /** Features */
            features: {
                [key: string]: unknown;
            }[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KpiRow
         * @description National-level yield estimate for one crop, for one season x year, per
         *     src/agritwin/survey/ (geo_level == "national"). One row per MVP crop, not a single
         *     blended number, so each keeps its own CI and reliability.
         */
        KpiRow: {
            crop: components["schemas"]["Crop"];
            season: components["schemas"]["Season"];
            /** Year */
            year: number;
            /** Yield Kg Ha */
            yield_kg_ha: number;
            /** Yield Kg Ha Ci Low */
            yield_kg_ha_ci_low?: number | null;
            /** Yield Kg Ha Ci High */
            yield_kg_ha_ci_high?: number | null;
            /** N Plots */
            n_plots: number;
            reliability: components["schemas"]["Reliability"];
        };
        /**
         * MetaResponse
         * @description Crops, seasons, years and districts that actually have data behind them, so the
         *     frontend never hardcodes scope that could drift from data/public/.
         */
        MetaResponse: {
            /** Crops */
            crops: components["schemas"]["Crop"][];
            /** Seasons */
            seasons: components["schemas"]["Season"][];
            /** Years */
            years: number[];
            /** Districts */
            districts: components["schemas"]["DistrictInfo"][];
            /** Data Version */
            data_version: string;
            /** Last Updated */
            last_updated?: string | null;
        };
        /**
         * NowcastCurveRow
         * @description District-level NDVI and CHIRPS rainfall signal at one lead time into a season,
         *     against its own multi-year climatology (MODIS 2001-2018, CHIRPS 1991-2020), per
         *     src/agritwin/models/nowcast.py's build_curve_table. Not crop-specific: the
         *     satellite signal is the same regardless of which crop is grown in that district.
         */
        NowcastCurveRow: {
            /** District Code */
            district_code: number;
            season: components["schemas"]["Season"];
            /** Year */
            year: number;
            /** Lead Months */
            lead_months: number;
            /** Ndvi Mean */
            ndvi_mean: number;
            /** Ndvi Climatology Mean */
            ndvi_climatology_mean: number;
            /** Ndvi Anomaly */
            ndvi_anomaly: number;
            /** Rainfall Mm */
            rainfall_mm: number;
            /** Rainfall Climatology Mm */
            rainfall_climatology_mm: number;
            /** Rainfall Anomaly */
            rainfall_anomaly: number;
        };
        /**
         * NowcastRow
         * @description One district's early yield estimate for one crop x season x year x lead time,
         *     from src/agritwin/models/nowcast.py's leave-one-year-out out-of-fold predictions.
         *     `model` is whichever of the 4 candidates had the lowest backtest MAPE for this crop
         *     x lead_months (see /backtest and data/public/nowcast_backtest.csv); per
         *     docs/decisions.md 2026-09-24, that is often baseline_district_mean, not a fancier
         *     model, and this field says which one was actually used. `ci_low`/`ci_high` are a
         *     normal-approximation interval from that model's own backtest residual spread, per
         *     CLAUDE.md golden rule 6. `is_backtest` is True for every row currently served: every
         *     year here has a completed SAS survey, so this is 2019-2025 historical hold-out data,
         *     not a live in-season prediction.
         */
        NowcastRow: {
            /** District Code */
            district_code: number;
            crop: components["schemas"]["Crop"];
            season: components["schemas"]["Season"];
            /** Year */
            year: number;
            /** Lead Months */
            lead_months: number;
            /** Model */
            model: string;
            /** Predicted Yield Kg Ha */
            predicted_yield_kg_ha: number;
            /** Ci Low */
            ci_low: number;
            /** Ci High */
            ci_high: number;
            /** Actual Yield Kg Ha */
            actual_yield_kg_ha?: number | null;
            /** Is Backtest */
            is_backtest: boolean;
            reliability: components["schemas"]["Reliability"];
        };
        /**
         * Reliability
         * @description Matches src/agritwin/survey/core.py's add_reliability_flag output.
         * @enum {string}
         */
        Reliability: "ok" | "use_with_caution" | "suppressed";
        /**
         * ScenarioRow
         * @description One lever configuration's predicted mean yield for one district x crop, per
         *     src/agritwin/models/scenario.py. Model-based estimate, not causal (CLAUDE.md rule
         *     5): a hypothetical input to the driver model, not a simulation of a real
         *     intervention. Same season caveat as DriverRow/BacktestRow: season is accepted but
         *     has no effect, since the driver model pools both seasons.
         */
        ScenarioRow: {
            crop: components["schemas"]["Crop"];
            /** District Code */
            district_code: number;
            /** Improved Seed */
            improved_seed: boolean;
            /** Inorganic Fert */
            inorganic_fert: boolean;
            /** Organic Fert */
            organic_fert: boolean;
            /** Irrigated */
            irrigated: boolean;
            /** Mean Yield Kg Ha */
            mean_yield_kg_ha: number;
            /** Ci Low */
            ci_low: number;
            /** Ci High */
            ci_high: number;
            /** N Plots */
            n_plots: number;
            reliability: components["schemas"]["Reliability"];
        };
        /**
         * Season
         * @description Seasons A and B only; Season C is excluded from MVP (see src/agritwin/CLAUDE.md).
         * @enum {string}
         */
        Season: "A" | "B";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * YearlyGap
         * @description One year's actual vs. attainable yield for a district, per
         *     src/agritwin/models/attainable.py.
         */
        YearlyGap: {
            /** Year */
            year: number;
            /** Actual Yield Kg Ha */
            actual_yield_kg_ha: number;
            /** Attainable Yield Kg Ha */
            attainable_yield_kg_ha?: number | null;
            /** Yield Gap Kg Ha */
            yield_gap_kg_ha?: number | null;
            /** Yield Gap Pct */
            yield_gap_pct?: number | null;
            reliability: components["schemas"]["Reliability"];
        };
        /**
         * YearlyYield
         * @description One year's district-level weighted yield estimate, per src/agritwin/survey/.
         */
        YearlyYield: {
            /** Year */
            year: number;
            /** Yield Kg Ha */
            yield_kg_ha: number;
            /** Yield Kg Ha Ci Low */
            yield_kg_ha_ci_low?: number | null;
            /** Yield Kg Ha Ci High */
            yield_kg_ha_ci_high?: number | null;
            reliability: components["schemas"]["Reliability"];
        };
        /**
         * YieldGapRow
         * @description One district x crop x season x year yield gap figure. Every numeric estimate
         *     carries its confidence interval (where computed) and a reliability flag, per
         *     api/CLAUDE.md: a "suppressed" row is still returned so the frontend can grey it out,
         *     not silently omitted.
         */
        YieldGapRow: {
            /** District Code */
            district_code: number;
            crop: components["schemas"]["Crop"];
            season: components["schemas"]["Season"];
            /** Year */
            year: number;
            /** Actual Yield Kg Ha */
            actual_yield_kg_ha: number;
            /** Actual Yield Kg Ha Ci Low */
            actual_yield_kg_ha_ci_low?: number | null;
            /** Actual Yield Kg Ha Ci High */
            actual_yield_kg_ha_ci_high?: number | null;
            /** Attainable Yield Kg Ha */
            attainable_yield_kg_ha?: number | null;
            /** Yield Gap Kg Ha */
            yield_gap_kg_ha?: number | null;
            /** Yield Gap Pct */
            yield_gap_pct?: number | null;
            /** N Plots */
            n_plots: number;
            reliability: components["schemas"]["Reliability"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_districts_api_v1_districts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoJSONResponse"];
                };
            };
        };
    };
    get_yield_gap_api_v1_yield_gap_get: {
        parameters: {
            query: {
                /** @description MVP crop */
                crop: components["schemas"]["Crop"];
                /** @description A or B */
                season: components["schemas"]["Season"];
                /** @description Survey year, e.g. 2024 */
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YieldGapRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_drivers_api_v1_drivers_get: {
        parameters: {
            query: {
                /** @description MVP crop */
                crop: components["schemas"]["Crop"];
                /** @description A or B. Currently has no effect: see DriverRow docstring */
                season: components["schemas"]["Season"];
                /** @description NISR district_code; omit for the global (all-districts) summary */
                district?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backtest_api_v1_backtest_get: {
        parameters: {
            query: {
                /** @description MVP crop */
                crop: components["schemas"]["Crop"];
                /** @description A or B. Currently has no effect: see BacktestRow docstring */
                season: components["schemas"]["Season"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_nowcast_api_v1_nowcast_get: {
        parameters: {
            query: {
                /** @description MVP crop */
                crop: components["schemas"]["Crop"];
                /** @description A or B */
                season: components["schemas"]["Season"];
                /** @description Season year, e.g. 2024 */
                year: number;
                /** @description Lead months into the season: 2, 3 or 4 */
                lead?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NowcastRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_nowcast_curve_api_v1_nowcast__code__curve_get: {
        parameters: {
            query: {
                /** @description A or B */
                season: components["schemas"]["Season"];
                /** @description Season year, e.g. 2024 */
                year: number;
            };
            header?: never;
            path: {
                code: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NowcastCurveRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    get_kpis_api_v1_kpis_get: {
        parameters: {
            query: {
                /** @description Survey year, e.g. 2024 */
                year: number;
                /** @description A or B */
                season: components["schemas"]["Season"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_district_profile_api_v1_districts__code__profile_get: {
        parameters: {
            query: {
                /** @description MVP crop */
                crop: components["schemas"]["Crop"];
                /** @description A or B. Has no effect on top_drivers: see DriverRow docstring */
                season: components["schemas"]["Season"];
            };
            header?: never;
            path: {
                code: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistrictProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_api_v1_scenario__code__get: {
        parameters: {
            query: {
                /** @description MVP crop */
                crop: components["schemas"]["Crop"];
                /** @description A or B. Currently has no effect: see ScenarioRow docstring */
                season: components["schemas"]["Season"];
            };
            header?: never;
            path: {
                code: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brief_api_v1_briefs__code__pdf_get: {
        parameters: {
            query?: {
                /** @description Accepted for API-shape compatibility. Has no effect, see docstring. */
                crop?: components["schemas"]["Crop"] | null;
                /** @description Accepted for API-shape compatibility. Has no effect, see docstring. */
                season?: components["schemas"]["Season"] | null;
            };
            header?: never;
            path: {
                code: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
