/** Offline fallback: reads web/public/static-data/ (generated by `make export`, see
 * src/agritwin/export/static_data.py) instead of the live API. Used only when the real
 * API is unreachable (see client.ts's apiGet) — every endpoint here is a filter, or a
 * small composition of filters, over the same files api/app/data_store.py loads, mirroring
 * each router's own logic. Not a general-purpose client; only handles the shapes this
 * app's hooks actually request.
 */

type Params = Record<string, string | number>

const cache = new Map<string, Promise<unknown>>()

function loadStatic<T>(file: string): Promise<T> {
  let pending = cache.get(file) as Promise<T> | undefined
  if (!pending) {
    pending = fetch(`/static-data/${file}`).then((response) => {
      if (!response.ok) throw new Error(`offline fallback missing: ${file}`)
      return response.json() as Promise<T>
    })
    cache.set(file, pending)
  }
  return pending
}

interface DistrictFeature {
  properties: { district_code: number; district_name: string }
}
interface DistrictCollection {
  features: DistrictFeature[]
}

async function districtName(code: number): Promise<string> {
  const geojson = await loadStatic<DistrictCollection>('districts.geojson')
  return (
    geojson.features.find((f) => f.properties.district_code === code)?.properties
      .district_name ?? ''
  )
}

async function buildDistrictProfile(code: number, params?: Params) {
  const [districtYield, yieldGap, driversByDistrict, zones] = await Promise.all([
    loadStatic<Record<string, unknown>[]>('district_yield.json'),
    loadStatic<Record<string, unknown>[]>('yield_gap.json'),
    loadStatic<Record<string, unknown>[]>('drivers_by_district.json'),
    loadStatic<Record<string, unknown>[]>('district_zones.json'),
  ])
  const name = await districtName(code)

  const yieldTrend = districtYield
    .filter(
      (r) =>
        r.geo_level === 'district' &&
        Number(r.geo_code) === code &&
        r.crop === params?.crop &&
        r.season === params?.season,
    )
    .sort((a, b) => Number(a.year) - Number(b.year))
    .map((r) => ({
      year: r.year,
      yield_kg_ha: r.yield_kg_ha,
      yield_kg_ha_ci_low: r.yield_kg_ha_ci_low,
      yield_kg_ha_ci_high: r.yield_kg_ha_ci_high,
      reliability: r.reliability,
    }))

  const gapTrend = yieldGap
    .filter(
      (r) =>
        Number(r.district_code) === code &&
        r.crop === params?.crop &&
        r.season === params?.season,
    )
    .sort((a, b) => Number(a.year) - Number(b.year))
    .map((r) => ({
      year: r.year,
      actual_yield_kg_ha: r.actual_yield_kg_ha,
      attainable_yield_kg_ha: r.attainable_yield_kg_ha,
      yield_gap_kg_ha: r.yield_gap_kg_ha,
      yield_gap_pct: r.yield_gap_pct,
      reliability: r.reliability,
    }))

  const topDrivers = driversByDistrict
    .filter((r) => Number(r.district_code) === code && r.crop === params?.crop)
    .sort((a, b) => Number(b.mean_abs_shap) - Number(a.mean_abs_shap))
    .slice(0, 5)

  const thisZone = zones.find((z) => Number(z.nisr_district_code) === code)
  const peerCodes = thisZone
    ? zones
        .filter((z) => z.zone_id === thisZone.zone_id && Number(z.nisr_district_code) !== code)
        .map((z) => Number(z.nisr_district_code))
    : []
  const peerDistricts = await Promise.all(
    peerCodes.map(async (peerCode) => ({
      district_code: peerCode,
      district_name: await districtName(peerCode),
    })),
  )

  return {
    district_code: code,
    district_name: name,
    crop: params?.crop,
    yield_trend: yieldTrend,
    gap_trend: gapTrend,
    top_drivers: topDrivers,
    peer_districts: peerDistricts,
  }
}

const DISTRICT_PROFILE = /^\/districts\/(\d+)\/profile$/
const SCENARIO = /^\/scenario\/(\d+)$/
const NOWCAST_CURVE = /^\/nowcast\/(\d+)\/curve$/

export async function staticGet<T>(path: string, params?: Params): Promise<T> {
  if (path === '/meta') return loadStatic<T>('meta.json')
  if (path === '/districts') return loadStatic<T>('districts.geojson')

  if (path === '/kpis') {
    const rows = await loadStatic<Record<string, unknown>[]>('district_yield.json')
    return rows.filter(
      (r) =>
        r.geo_level === 'national' &&
        r.season === params?.season &&
        String(r.year) === String(params?.year),
    ) as T
  }

  if (path === '/yield-gap') {
    const rows = await loadStatic<Record<string, unknown>[]>('yield_gap.json')
    return rows.filter(
      (r) =>
        r.crop === params?.crop &&
        r.season === params?.season &&
        String(r.year) === String(params?.year),
    ) as T
  }

  if (path === '/drivers') {
    if (params?.district != null) {
      const rows = await loadStatic<Record<string, unknown>[]>('drivers_by_district.json')
      return rows.filter(
        (r) => r.crop === params.crop && Number(r.district_code) === Number(params.district),
      ) as T
    }
    const rows = await loadStatic<Record<string, unknown>[]>('drivers.json')
    return rows.filter((r) => r.crop === params?.crop) as T
  }

  if (path === '/backtest') {
    const rows = await loadStatic<Record<string, unknown>[]>('backtest.json')
    return rows.filter((r) => r.crop === params?.crop) as T
  }

  if (path === '/nowcast') {
    const rows = await loadStatic<Record<string, unknown>[]>('nowcast.json')
    return rows.filter(
      (r) =>
        r.crop === params?.crop &&
        r.season === params?.season &&
        String(r.year) === String(params?.year) &&
        String(r.lead_months) === String(params?.lead),
    ) as T
  }

  const profileMatch = path.match(DISTRICT_PROFILE)
  if (profileMatch) {
    return buildDistrictProfile(Number(profileMatch[1]), params) as Promise<T>
  }

  const scenarioMatch = path.match(SCENARIO)
  if (scenarioMatch) {
    const code = Number(scenarioMatch[1])
    const rows = await loadStatic<Record<string, unknown>[]>('scenario.json')
    return rows.filter((r) => Number(r.district_code) === code && r.crop === params?.crop) as T
  }

  const curveMatch = path.match(NOWCAST_CURVE)
  if (curveMatch) {
    const code = Number(curveMatch[1])
    const rows = await loadStatic<Record<string, unknown>[]>('nowcast_curve.json')
    return rows.filter(
      (r) =>
        Number(r.district_code) === code &&
        r.season === params?.season &&
        String(r.year) === String(params?.year),
    ) as T
  }

  // Not mirrored: GET /briefs/{code}.pdf has no JSON form.
  throw new Error(`No offline fallback available for ${path}`)
}
