"""Static JSON mirror of data/public/, for the web app's offline fallback.

Per web/CLAUDE.md: `public/static-data/` is "a JSON mirror of the API for offline
fallback... generated by make export". Every API endpoint (checked against
api/app/data_store.py and every router in api/app/routers/) is a plain filter, or a
small composition of filters, over these same CSV/GeoJSON files loaded wholesale into
memory; there is no server-side modeling or join that happens only in Python. So the
mirror here is these same files, converted to JSON, plus one precomputed `meta.json`
(mirroring meta.py's own crops/seasons/years/districts logic) since that endpoint reads
two other files rather than one of its own.

Not mirrored: `GET /briefs/{code}.pdf` (a rendered PDF has no JSON form) and anything
that would need the live API's request validation (invalid crop/season/year values);
the frontend's fallback path is expected to pass through only values it already knows
are valid, from `/meta`.
"""

from __future__ import annotations

import json
from pathlib import Path

import loguru
import pandas as pd

DATA_PUBLIC = Path(__file__).resolve().parents[3] / "data" / "public"

logger = loguru.logger

# public/ CSV filename -> static-data/ JSON filename. Same nine files
# api/app/data_store.py loads, one to one.
CSV_MIRRORS = {
    "yield_gap.csv": "yield_gap.json",
    "drivers.csv": "drivers.json",
    "drivers_by_district.csv": "drivers_by_district.json",
    "nowcast_backtest.csv": "backtest.json",
    "district_yield.csv": "district_yield.json",
    "district_zones.csv": "district_zones.json",
    "scenario.csv": "scenario.json",
    "nowcast.csv": "nowcast.json",
    "nowcast_curve.csv": "nowcast_curve.json",
}


def build_meta(district_yield: pd.DataFrame | None, districts_geojson: dict | None) -> dict:
    """Same logic as api/app/routers/meta.py's get_meta(), against the same two
    sources, so the offline `/meta` mirror matches the live endpoint's shape exactly."""
    years: list[int] = []
    if district_yield is not None:
        years = sorted(int(y) for y in district_yield["year"].unique())

    districts: list[dict] = []
    if districts_geojson:
        for feature in districts_geojson["features"]:
            props = feature["properties"]
            code = props.get("district_code")
            if code is not None:
                districts.append({"district_code": code, "district_name": props["district_name"]})
        districts.sort(key=lambda d: d["district_code"])

    return {
        "crops": ["maize", "beans", "irish_potato", "sorghum"],
        "seasons": ["A", "B"],
        "years": years,
        "districts": districts,
        "data_version": "2026.10.0",  # matches api/app/data_store.py's DATA_VERSION
        "last_updated": None,  # a static export has no meaningful build-time "last updated"
    }


def run(public_dir: Path = DATA_PUBLIC, out_dir: Path | None = None) -> None:
    out_dir = out_dir or Path(__file__).resolve().parents[3] / "web" / "public" / "static-data"
    out_dir.mkdir(parents=True, exist_ok=True)

    district_yield_df: pd.DataFrame | None = None
    for csv_name, json_name in CSV_MIRRORS.items():
        csv_path = public_dir / csv_name
        if not csv_path.exists():
            logger.warning(f"{csv_name} not found, skipping {json_name}")
            continue
        df = pd.read_csv(csv_path)
        if csv_name == "district_yield.csv":
            district_yield_df = df
        df.to_json(out_dir / json_name, orient="records")
        logger.info(f"wrote {len(df)} rows to {out_dir / json_name}")

    geojson_path = public_dir / "geo" / "rwanda_districts_simplified.geojson"
    districts_geojson: dict | None = None
    if geojson_path.exists():
        districts_geojson = json.loads(geojson_path.read_text())
        (out_dir / "districts.geojson").write_text(json.dumps(districts_geojson))
        n = len(districts_geojson.get("features", []))
        logger.info(f"wrote {n} districts to districts.geojson")
    else:
        logger.warning(f"{geojson_path} not found, skipping districts.geojson")

    meta = build_meta(district_yield_df, districts_geojson)
    (out_dir / "meta.json").write_text(json.dumps(meta))
    logger.info(f"wrote meta.json ({len(meta['districts'])} districts, {len(meta['years'])} years)")


if __name__ == "__main__":
    run()
